# Numpy 101

The goal of this challenge is to get familiar with the Numpy library, manipulate multidimensional arrays and apply some linear algebra operations without using `for` loops.

💡 Do not forget to keep the [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) closed during this challenge.

In [1]:
import numpy as np # Run this cell!

---

**Q1** - Create a null vector (i.e. with only zeros `0`) of size 10 and assign it to a variable named `ten_zeros`. 

It should look like this:

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.zeros.html"><code>numpy.zeros</code></a></p>
</details>

In [20]:
ten_zeros = np.zeros(10)
ten_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

**Q2** - Create a vector with values from 5 to 10 and assign it to a variable named `five_to_ten`.

It should look like this:

```
array([ 5,  6,  7,  8,  9, 10])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html"><code>numpy.arange</code></a></p>
</details>

In [22]:
five_to_ten = np.arange(5, 11)
five_to_ten

array([ 5,  6,  7,  8,  9, 10])

---

**Q3** - Create the following matrix as a NumPy `ndarray` and assign it to a variable named `A`:

$
A = 
\begin{pmatrix}
5 & 9 & 7\\
1 & 0 & 3
\end{pmatrix}
$

<br>
<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.array.html"><code>numpy.array</code></a></p>
    <p>Checkout more about the relationship between<a href="https://stackoverflow.com/questions/15879315/what-is-the-difference-between-ndarray-and-array-in-numpy"><code>numpy.array and numpy.ndarray</code></a></p>
</details>

In [30]:
A = np.array([[5, 9, 7],[1, 0, 3]])
A

array([[5, 9, 7],
       [1, 0, 3]])

---
**Q4** - Create the following matrix without using the `np.array()` constructor and assign it to a variable named `B`:

$
B = 
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
$

In [33]:
B = np.ones((2,2))
B

array([[1., 1.],
       [1., 1.]])

---

**Q5** - Create a vector of 20 elements evenly spaced between `-1` and `1` and assign it to a variable named `lin_twenty`.

It should look like this:

```
array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html"><code>numpy.linspace</code></a></p>
</details>

In [37]:
lin_twenty = np.linspace(-1, 1, 20)
lin_twenty

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

---

**Q6** - Create a 3x3 identity matrix and assign it to a variable named `C`:

$
C = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.eye.html"><code>numpy.eye</code></a></p>
</details>

In [41]:
C = np.identity(3)
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

**Q7** - Create the following `ndarray` and assign it to a variable named `D`:  

$
D = 
\begin{pmatrix}
2 & 9 & 7 & 3 & 1 & 5
\end{pmatrix}
$

Reshape `D` into a 2x3 matrix and assign it to a variable named `E`:

$
E = 
\begin{pmatrix}
2 & 9 & 7\\
3 & 1 & 5
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.reshape.html"><code>numpy.reshape</code></a></p>
</details>

In [49]:
D = np.array((2, 9, 7, 3, 1, 5))
E = np.reshape(D, (2,3))
E

array([[2, 9, 7],
       [3, 1, 5]])

---

**Q8** - Create a 8x8 checkboard matrix and assign it to a variable named `F`:

$
F = 
\begin{pmatrix}
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.tile.html"><code>numpy.tile</code></a></p>
</details>

In [58]:
preF = np.tile([1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1], 4)
F = np.reshape(preF, (8,8))
F

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

---

**Q9**: Select the second column of this `ndarray` `G`, reshape it as an `ndarray` of 4 lines and 1 column and assign it to a variable named `reshaped_G`:

$
reshaped\_G = 
\begin{pmatrix}
0.?\\
0.?\\
0.?\\
0.?\\
\end{pmatrix}
$

In [62]:
G = np.random.random((4, 5))
print(G)

[[0.75124188 0.79081436 0.13776833 0.34212778 0.96210755]
 [0.35235662 0.57408401 0.55558266 0.97885987 0.92055511]
 [0.94963631 0.22078953 0.51361374 0.96166419 0.22281171]
 [0.08058834 0.5531539  0.31823279 0.19967493 0.94596952]]


In [67]:
col_G = G[0:4,1]
reshaped_G = np.reshape(col_G,(4,1))
reshaped_G

array([[0.79081436],
       [0.57408401],
       [0.22078953],
       [0.5531539 ]])

---

**Q10** - Compute the sum of matrixes `H` and `I` and store the result into a variable `hi_sum`:

$
H = 
\begin{pmatrix}
0 & 4\\
-4 & -3\\
1 & 1
\end{pmatrix}
$

$
I =
\begin{pmatrix}
0 & 1\\
1 & -1\\
2 & 3
\end{pmatrix}
$

$
H + I = ?
$


In [69]:
# Here we demonstrate two different approaches to creating a (3,2) Matrix
H = np.array([0, 4, -4, -3, 1, 1]).reshape(3, 2)
print('H: \n', H)
I = np.array([[0, 1], [1, -1], [2, 3]])
print('I: \n', I)

H: 
 [[ 0  4]
 [-4 -3]
 [ 1  1]]
I: 
 [[ 0  1]
 [ 1 -1]
 [ 2  3]]


In [70]:
hi_sum = np.sum(H,I)
hi_sum

TypeError: only integer scalar arrays can be converted to a scalar index

## Check your code!

Run the cell below to check your code:

In [ ]:
from nbresult import ChallengeResult

result = ChallengeResult('numpy',
    ten=ten_zeros,
    from_five=five_to_ten,
    A=A,
    B=B,
    lin_twenty=lin_twenty,
    C=C,
    E=E,
    F=F,
    reshaped_G=reshaped_G,
    hi_sum=hi_sum
)
result.write()
print(result.check())